[package]
name = "bls_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls = { git = "https://github.com/ZenGo-X/multi-party-bls" }